config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "user/registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :carts
  resources :discounted_sales
  resources :discounted_products
  resources :product_categories
  resources :products
  resources :addresses

  root 'products#index'
  get  'order/create'
  get  'user/profile'
  get  'sessions/new'
  get  'generate/controller'
  get  'generate/order'
  get  'generate/cretae'
  get  'myCart'               => 'sessions#myCart'
  get  'add_to_cart'          => 'sessions#add_to_cart'
  get  'add_quantity'         => 'sessions#add_quantity'
  get  'deduct_quantity'      => 'sessions#deduct_quantity'
  get  'remove_cart'          => 'sessions#remove_cart'
  get  'delivery_address'     => 'sessions#delivery_address'
  get  'place_order'          => 'sessions#place_order'
  post 'add_delivery_address' => 'sessions#add_delivery_address'
  post '/hook'                => 'order#hook'
  get  '/order_receipt'       => 'order#order_receipt'
  get  '/purchased_orders'    => 'order#purchased_orders'

end

app/models/discounted_product.rb
class DiscountedProduct < ActiveRecord::Base
  belongs_to :discounted_sale
  belongs_to :product
end

app/controllers/discounted_products_controller.rb
class DiscountedProductsController < ApplicationController
  before_action :set_discounted_product, only: [:show, :edit, :update, :destroy]

  # GET /discounted_products
  # GET /discounted_products.json
  def index
    @discounted_products = DiscountedProduct.all
  end

  # GET /discounted_products/1
  # GET /discounted_products/1.json
  def show
  end

  # GET /discounted_products/new
  def new
    @discounted_product = DiscountedProduct.new
  end

  # GET /discounted_products/1/edit
  def edit
  end

  # POST /discounted_products
  # POST /discounted_products.json
  def create
    @discounted_product = DiscountedProduct.new(discounted_product_params)

    respond_to do |format|
      if @discounted_product.save
        format.html { redirect_to @discounted_product, notice: 'Discounted product was successfully created.' }
        format.json { render :show, status: :created, location: @discounted_product }
      else
        format.html { render :new }
        format.json { render json: @discounted_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounted_products/1
  # PATCH/PUT /discounted_products/1.json
  def update
    respond_to do |format|
      if @discounted_product.update(discounted_product_params)
        format.html { redirect_to @discounted_product, notice: 'Discounted product was successfully updated.' }
        format.json { render :show, status: :ok, location: @discounted_product }
      else
        format.html { render :edit }
        format.json { render json: @discounted_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounted_products/1
  # DELETE /discounted_products/1.json
  def destroy
    @discounted_product.destroy
    respond_to do |format|
      format.html { redirect_to discounted_products_url, notice: 'Discounted product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discounted_product
      @discounted_product = DiscountedProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discounted_product_params
      params.require(:discounted_product).permit(:discounted_sale_id, :product_id)
    end
end

app/helpers/discounted_products_helper.rb
module DiscountedProductsHelper
end

app/views/discounted_products/_form.html.erb
<%= form_for(@discounted_product) do |f| %>
  <% if @discounted_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discounted_product.errors.count, "error") %> prohibited this discounted_product from being saved:</h2>

      <ul>
      <% @discounted_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :discounted_sale_id %><br>
    <%= f.number_field :discounted_sale_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discounted_products/edit.html.erb
<h1>Editing Discounted Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @discounted_product %> |
<%= link_to 'Back', discounted_products_path %>

app/views/discounted_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Discounted Products</h1>

<table>
  <thead>
    <tr>
      <th>Discounted sale</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounted_products.each do |discounted_product| %>
      <tr>
        <td><%= discounted_product.discounted_sale_id %></td>
        <td><%= discounted_product.product_id %></td>
        <td><%= link_to 'Show', discounted_product %></td>
        <td><%= link_to 'Edit', edit_discounted_product_path(discounted_product) %></td>
        <td><%= link_to 'Destroy', discounted_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discounted product', new_discounted_product_path %>

app/views/discounted_products/new.html.erb
<h1>New Discounted Product</h1>

<%= render 'form' %>

<%= link_to 'Back', discounted_products_path %>

app/views/discounted_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discounted sale:</strong>
  <%= @discounted_product.discounted_sale_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @discounted_product.product_id %>
</p>

<%= link_to 'Edit', edit_discounted_product_path(@discounted_product) %> |
<%= link_to 'Back', discounted_products_path %>