config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "user/registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :carts
  resources :discounted_sales
  resources :discounted_products
  resources :product_categories
  resources :products
  resources :addresses

  root 'products#index'
  get  'order/create'
  get  'user/profile'
  get  'sessions/new'
  get  'generate/controller'
  get  'generate/order'
  get  'generate/cretae'
  get  'myCart'               => 'sessions#myCart'
  get  'add_to_cart'          => 'sessions#add_to_cart'
  get  'add_quantity'         => 'sessions#add_quantity'
  get  'deduct_quantity'      => 'sessions#deduct_quantity'
  get  'remove_cart'          => 'sessions#remove_cart'
  get  'delivery_address'     => 'sessions#delivery_address'
  get  'place_order'          => 'sessions#place_order'
  post 'add_delivery_address' => 'sessions#add_delivery_address'
  post '/hook'                => 'order#hook'
  get  '/order_receipt'       => 'order#order_receipt'
  get  '/purchased_orders'    => 'order#purchased_orders'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :product_quantity %><br>
    <%= f.number_field :product_quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Your Cart</h1>

app/views/carts/myCart.html.erb
<style type="text/css">
  th{
    font-size: 25px;
  }
</style>
<script type="text/javascript">
  $(document).ready(function(){
    $(".glyphicon-plus").click(function(){
      var id = this.id.split('_');
      $.ajax({
        url: "<%= add_quantity_path %>",
        type: "GET",
        data:{id: id[1]},
        success: function(data) {

        }
      });
    });

    $(".glyphicon-minus").click(function(){
      var id = this.id.split('_');
      $.ajax({
        url: "<%= deduct_quantity_path %>",
        type: "GET",
        data:{id: id[1]},
        success: function(data) {

        }
      });
    });

    $(".remove_cart").click(function(){
      var id = this.id.split('_');
      var total_price = $('#total_price').text()
      var item_price = $('#item_price_' + id[2]).text();
      $.ajax({
        url: "<%= remove_cart_path %>",
        type: "GET",
        data:{id: id[2]},
        success: function(data) {
          document.getElementById(data.cart_id).remove()
          $('#badge').html(data.cart_count)
          var new_price = total_price - item_price;
          $('#total_price').html(new_price)
          if($('#total_price').text() == 0){
            $('#cart_table').remove()
            $('#empty_cart_heading').show();
          }
        }
      });
    });
  });
</script>

<div style="width: 60%;margin: auto;">
<h1>Your Cart</h1>
<h3 id="empty_cart_heading" style="text-align: center; display: none;">You have no items in your cart right now!</h3>
<table class="table" id="cart_table">
  <% if @carts.blank? %>
    <h3 style="text-align: center;">You have no items in your cart right now!</h3>
  <% else %>
    <thead class="thead-default">
      <tr>
        <th></th>
        <th>Item</th>
        <th>Quantity</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @total_price = 0 %>
      <% @carts.each do |cart|%>
        <tr id="<%= cart.id %>">
          <td><%= image_tag(cart.product.image.url, size: '150x100') if cart.product.image? %></td>
          <td><%= cart.product.name %></td>
          <td>
            <a href=""><span class="glyphicon glyphicon-plus" id="plus_<%= cart.id %>"></span></a>
            <input type="mumber" value="<%= cart.product_quantity%>" style="width: 45px; display: inline-block;" class="form-control" disabled>
            <% if cart.product_quantity > 1%>
              <a href=""><span class="glyphicon glyphicon-minus" id="minus_<%= cart.id %>"></span></a>
            <% end %>
          </td>
          <% if cart.product.discounted_price.present? %>
            <td id="item_price_<%= cart.id %>"><%= @item_price = cart.product.discounted_price*cart.product_quantity %></td>
          <% else %>
            <td id="item_price_<%= cart.id %>"><%= @item_price = cart.product.price*cart.product_quantity %></td>
          <% end %>
          <td>
            <input type="button" class="btn btn-danger remove_cart" value="Remove From Cart"
              id="remove_cart_<%= cart.id %>"></input>
          </td>
        </tr>
        <% @total_price = @total_price + @item_price %>
      <% end %>
    <tr>
      <td colspan="2" style="font-size: 30px;text-align: right;">
        <b>Estimated Total</b>
      </td>
      <td style="font-size: 30px;">
        Rs:
      </td>
      <td id="total_price" style="font-size: 30px;text-align:left;">
        <%= @total_price %>
      </td>
      <td style="font-size: 30px;">
        <%= link_to "Check Out", addresses_path, class:"btn btn-primary",data-toggle:"modal" data-target:"#myModal" %>
      </td>
      <!-- Modal -->
      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Choose Your Address For Shipping</h4>
            </div>
            <div class="modal-body">
            <% current_user.addresses.each do |address| %>
              <p><%= address.address %></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </tr>
    </tbody>
  <% end %>
</table>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cart.product_id %>
</p>

<p>
  <strong>Product quantity:</strong>
  <%= @cart.product_quantity %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>