config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "user/registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :carts
  resources :discounted_sales
  resources :discounted_products
  resources :product_categories
  resources :products
  resources :addresses

  root 'products#index'
  get  'order/create'
  get  'user/profile'
  get  'sessions/new'
  get  'generate/controller'
  get  'generate/order'
  get  'generate/cretae'
  get  'myCart'               => 'sessions#myCart'
  get  'add_to_cart'          => 'sessions#add_to_cart'
  get  'add_quantity'         => 'sessions#add_quantity'
  get  'deduct_quantity'      => 'sessions#deduct_quantity'
  get  'remove_cart'          => 'sessions#remove_cart'
  get  'delivery_address'     => 'sessions#delivery_address'
  get  'place_order'          => 'sessions#place_order'
  post 'add_delivery_address' => 'sessions#add_delivery_address'
  post '/hook'                => 'order#hook'
  get  '/order_receipt'       => 'order#order_receipt'
  get  '/purchased_orders'    => 'order#purchased_orders'

end

app/models/discounted_sale.rb
class DiscountedSale < ActiveRecord::Base
  has_many :discounted_products
  has_many :products, through: :discounted_products
end

app/controllers/discounted_sales_controller.rb
class DiscountedSalesController < ApplicationController
  before_action :set_discounted_sale, only: [:show, :edit, :update, :destroy]

  # GET /discounted_sales
  # GET /discounted_sales.json
  def index
    @discounted_sales = DiscountedSale.all
  end

  # GET /discounted_sales/1
  # GET /discounted_sales/1.json
  def show
  end

  # GET /discounted_sales/new
  def new
    @discounted_sale = DiscountedSale.new
  end

  # GET /discounted_sales/1/edit
  def edit
  end

  # POST /discounted_sales
  # POST /discounted_sales.json
  def create
    @discounted_sale = DiscountedSale.new(discounted_sale_params)

    respond_to do |format|
      if @discounted_sale.save
        format.html { redirect_to @discounted_sale, notice: 'Discounted sale was successfully created.' }
        format.json { render :show, status: :created, location: @discounted_sale }
      else
        format.html { render :new }
        format.json { render json: @discounted_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounted_sales/1
  # PATCH/PUT /discounted_sales/1.json
  def update
    respond_to do |format|
      if @discounted_sale.update(discounted_sale_params)
        format.html { redirect_to @discounted_sale, notice: 'Discounted sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @discounted_sale }
      else
        format.html { render :edit }
        format.json { render json: @discounted_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounted_sales/1
  # DELETE /discounted_sales/1.json
  def destroy
    @discounted_sale.destroy
    respond_to do |format|
      format.html { redirect_to discounted_sales_url, notice: 'Discounted sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discounted_sale
      @discounted_sale = DiscountedSale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discounted_sale_params
      params.require(:discounted_sale).permit(:name, :discount_percent, :start_date, :end_date)
    end
end

app/helpers/discounted_sales_helper.rb
module DiscountedSalesHelper
end

app/views/discounted_sales/_form.html.erb
<%= form_for(@discounted_sale) do |f| %>
  <% if @discounted_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discounted_sale.errors.count, "error") %> prohibited this discounted_sale from being saved:</h2>

      <ul>
      <% @discounted_sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :discount_percent %><br>
    <%= f.number_field :discount_percent %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discounted_sales/edit.html.erb
<h1>Editing Discounted Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @discounted_sale %> |
<%= link_to 'Back', discounted_sales_path %>

app/views/discounted_sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Discounted Sales</h1>

<table>
  <thead>
    <tr>
      <th>Discount percent</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounted_sales.each do |discounted_sale| %>
      <tr>
        <td><%= discounted_sale.discount_percent %></td>
        <td><%= discounted_sale.start_date %></td>
        <td><%= discounted_sale.end_date %></td>
        <td><%= link_to 'Show', discounted_sale %></td>
        <td><%= link_to 'Edit', edit_discounted_sale_path(discounted_sale) %></td>
        <td><%= link_to 'Destroy', discounted_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discounted sale', new_discounted_sale_path %>

app/views/discounted_sales/new.html.erb
<h1>New Discounted Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', discounted_sales_path %>

app/views/discounted_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discount percent:</strong>
  <%= @discounted_sale.discount_percent %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @discounted_sale.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @discounted_sale.end_date %>
</p>

<%= link_to 'Edit', edit_discounted_sale_path(@discounted_sale) %> |
<%= link_to 'Back', discounted_sales_path %>