config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "user/registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :carts
  resources :discounted_sales
  resources :discounted_products
  resources :product_categories
  resources :products
  resources :addresses

  root 'products#index'
  get  'order/create'
  get  'user/profile'
  get  'sessions/new'
  get  'generate/controller'
  get  'generate/order'
  get  'generate/cretae'
  get  'myCart'               => 'sessions#myCart'
  get  'add_to_cart'          => 'sessions#add_to_cart'
  get  'add_quantity'         => 'sessions#add_quantity'
  get  'deduct_quantity'      => 'sessions#deduct_quantity'
  get  'remove_cart'          => 'sessions#remove_cart'
  get  'delivery_address'     => 'sessions#delivery_address'
  get  'place_order'          => 'sessions#place_order'
  post 'add_delivery_address' => 'sessions#add_delivery_address'
  post '/hook'                => 'order#hook'
  get  '/order_receipt'       => 'order#order_receipt'
  get  '/purchased_orders'    => 'order#purchased_orders'

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :category, class_name: 'ProductCategory'
  has_many :carts
  has_many :cart_items
  has_one :discounted_product
  has_one :discounted_sale, through: :discounted_product


  def discounted_price
    if discounted_sale.present? && discounted_sale.start_date <= Date.today && discounted_sale.end_date >= Date.today
      dp = (price-((price*discounted_sale.discount_percent)/100))
    end
    dp
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    # p params.inspect
    # p "abcdefg"
    # # abort
    if params[:product_category_id]
      @products = Product.where(category_id: params[:product_category_id])
    elsif params[:search_key]
      @products = Product.where("name LIKE ? OR description LIKE ?", "%#{params[:search_key]}%", "%#{params[:search_key]}%")
    else
      @products = Product.all
    end

    @discounted_sale = DiscountedSale.find_by("start_date <= ? and end_date >= ?", Date.today, Date.today)
    if @discounted_sale.present?
      @discounted_products = @discounted_sale.discounted_products
    end

    if session[:cart_id].present?
      @cart = MyCart.find(session[:cart_id].to_i)
    end
    # @products = @products.to_json
    # return @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if session[:cart_id].present?
      @cart = MyCart.find(session[:cart_id].to_i)
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id, :image, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">

  <div class="jumbotron" style="text-align: center;background-image: url(/assets/shopping.jpg); background-size: 2500px 1800px;">
    <h1><span style="color: black">Welcome to Shopoholic!</span></h1>
    <h1><span style="color: black">A Shop to Shop Everything</span></h1>
    <% if !user_signed_in? %>
      <a href="<%= new_user_registration_path %>" class="btn btn-primary" style="font-size: 22px;">Register</a>
    <% end %>
 </div>

  <% if @discounted_sale.present? %>
    <h3 style="text-align: center;"><b><%=@discounted_sale.name%> Sale. Flat <%= @discounted_sale.discount_percent %>% off!</b> <b>Ending on <%= @discounted_sale.end_date.to_date %></b></h3>
  <% end %>
  <% if @discounted_products.present? %>
    <ul id="flexiselDemo3">
      <% @discounted_products.each do |discounted_product| %>
        <li>
          <%= link_to image_tag(discounted_product.product.image.url, size: '300x300'), product_path(discounted_product.product.id) if discounted_product.product.image? %>
          <h3><%= discounted_product.product.name %></h3>
          <p style="text-align: center; font-size: 20px; margin-top: 20px;">Rs.<b><%= discounted_product.product.discounted_price %></b> <strike><b style="color: red;"><%= discounted_product.product.price%></b>
          </strike></p>
          <% if @cart.present? && @cart.cart_items.where(product_id:discounted_product.product.id).present?%>
            <input type="button" class="btn btn-success" disabled value="Added to cart" style="margin-top: 15px;"></input>
          <% else %>
            <input type="button" class="btn btn-default add_product product_item_<%= discounted_product.product.id %>" style="margin-top:15px;" value="Add To Cart"
            id="add_to_cart1_<%= discounted_product.product.id %>"></input>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <h1>All Products</h1>
  <% @products.each do |product| %>
    <div class="home_article_div">
      <div class="home_image_div">
        <%= link_to image_tag(product.image.url, size: '300x200'), product_path(product) if product.image?  %>
      </div>
      <div>
        <h3><%= product.name %></h3>
        <% if product.discounted_price.present? %>
          <p style="text-align: center; font-size: 20px;">Rs.<b><%= product.discounted_price %></b> <strike><b style="color: red;"><%= product.price%></b>
          </strike></p>
        <% else %>
          <p style="text-align: center; font-size: 20px;">Rs.<b><%= product.price%></b></p>
        <% end %>
      </div>
      <div class="home_button_div">
        <% if @cart.present? && @cart.cart_items.where(product_id:product.id).present?%>
          <input type="button" id="added" class="btn btn-success" disabled value="Added to cart" ></input>
        <% else %>
          <input type="button" class="btn btn-default add_product product_item_<%= product.id %>" value="Add To Cart" id="add_to_cart_<%= product.id %>"></input>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<script type="text/javascript">
  $(document).ready(function(){
     $("#flexiselDemo3").flexisel({
        visibleItems: 3,
        itemsToScroll: 1,
        autoPlay: {
            enable: true,
            interval: 5000,
            pauseOnHover: true
        }
    });

    $(".add_product").click(function(){
      var abc = this.id
      var id = this.id.split('_');
      $.ajax({
        url: "<%= add_to_cart_path %>",
        type: "GET",
        data:{product_id: id[3]},
        success: function(data) {
          $('#badge').html(data.cart_count);
          $('.product_item_'+id[3]).attr('value','Added To Cart')
          $('.product_item_'+id[3]).addClass('btn btn-success')
          $('.product_item_'+id[3]).prop("disabled",true)
        }
      });
    });
  });
</script>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
<style type="text/css">
  .image_div
  {
    float: left;
    margin-right:20px;
  }
</style>

<!-- ===========================Product details Section=========================== -->
  <div>
    <div class="image_div" >
      <%= image_tag( @product.image.url,alt: 'No Image for this product', height: "500", width: "600") %>
    </div>
    <div style="float: left;width: 450px;margin-left: 80px;" >
      <div class="panel panel-primary" style="width: inherit;">
        <div class="panel-heading">
          <h3 class="panel-title">Name</h3>
        </div>
        <div class="panel-body">
          <%= @product.name.upcase %>
        </div>
      </div>
      <div class="panel panel-info" style="width: inherit;">
        <div class="panel-heading">
          <h3 class="panel-title">Specifications</h3>
        </div>
        <div class="panel-body">
          <%= @product.description.html_safe %>
        </div>

      </div>
      <div class="panel panel-info" style="width: inherit;">
        <div class="panel-heading">
          <h3 class="panel-title">Price</h3>
        </div>
        <div class="panel-body">
          <% if @product.discounted_price.present? %>
            <p style="text-align: center; font-size: 20px;">Rs.<b><%= @product.discounted_price %></b> <strike><b style="color: red;"><%= @product.price%></b></strike>
            </p>
          <% else %>
            <p style="text-align: center; font-size: 20px;">Rs.<b><%= @product.price%></b></p>
          <% end %>
        </div>
        <div style="float: right; margin-top: 20px;">
          <% if @cart.present? && @cart.cart_items.where(product_id:@product.id).present?%>
            <input type="button" class="btn btn-success" disabled value="Added to cart"></input>
          <% else %>
            <input type="button" class="btn btn-default add_product" value="Add To Cart" id="add_to_cart_<%= @product.id %>"></input>
          <% end %>
        </div>
      </div>
    </div>
    <div>
      <div class="form-group">
      <%= form_for :product,name:'comment_form', html: { multipart: true } ,url: article_comments_path(@article) do |f| %>
        <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@comment.errors.count, "error") %> prohibited
              this comment from being saved:
            </h2>
            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.text_area :comment,rows: '3',class:'form-control',placeholder:'Write a comment',id:'comment_box'%></br>
        <% if user_signed_in? %>
          <p>
            <%= f.submit("Post Comment",class:'btn btn-primary btn-block',onclick: "return check()") %>
          </p>
        <% else %>
          <p>
            <%= f.submit("Post Comment",class:'btn btn-primary btn-block') %>
          </p>
        <% end %>
      <% end %>
    </div>
    </div>
  <div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".add_product").click(function(){
      var abc = this.id
      var id = this.id.split('_');
      $.ajax({
        url: "<%= add_to_cart_path %>",
        type: "GET",
        data:{product_id: id[3]},
        success: function(data) {
          $('#badge').html(data.cart_count);
          $('#add_to_cart_'+id[3]).attr('value','Added To Cart')
          $('#add_to_cart_'+id[3]).addClass('btn btn-success')
          $('#add_to_cart_'+id[3]).prop("disabled",true)
        }
      });
    });
  });
</script>